TopicScientific/TopicScientific/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from home.views import (
    home,
)
from accounts.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('topic/', include('topics.urls', 'topic')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

TopicScientific/topics/urls.py
from django.urls import path
from topics.views import (
    create_topic_view,
    detail_topic_view,
    edit_topic_view,
    edit_topic_super_user_view,
)

app_name = 'topic'

urlpatterns = [
    path('create/', create_topic_view, name='create'),
    path('<slug>/', detail_topic_view, name='detail'),
    path('<slug>/edit/', edit_topic_view, name='edit'),
    path('<slug>/edit_superuser/', edit_topic_super_user_view, name='edit_superuser'),

]

TopicScientific/home/models.py
from django.db import models

# Create your models here.

TopicScientific/topics/models.py
from django.db import models

from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver

# Create your models here.

class research_direction(models.Model):
    research_direction = models.CharField(max_length=50)

    def __str__(self):
        return self.research_direction


class rate(models.Model):
    rate = models.CharField(max_length=50)

    def __str__(self):
        return self.rate


class type(models.Model):
    type = models.CharField(max_length=50)

    def __str__(self):
        return self.type


class topic(models.Model):
    topic_name = models.CharField(max_length=255)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    research_direction = models.ForeignKey(research_direction, on_delete=models.CASCADE)
    type = models.ForeignKey(type, on_delete=models.CASCADE)
    rate = models.ForeignKey(rate, on_delete=models.CASCADE, blank=True, null=True)
    review_date = models.CharField(max_length=50, blank=True, null=True)
    content = models.TextField()
    date_upload = models.DateField(auto_now_add=True)
    slug = models.SlugField(blank=True, unique=True)
    process = models.CharField(max_length=10, default=0)

    def __str__(self):
        return self.topic_name

    def snippet(self):
        return self.content[:50] + '...'


def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + ".." + instance.topic_name)


pre_save.connect(pre_save_receiver, sender=topic)

TopicScientific/topics/forms.py
from django import forms
from topics.models import topic


class CreateTopicForm(forms.ModelForm):

    class Meta:
        model = topic
        fields = ['topic_name', 'research_direction', 'type', 'content']


class EditTopicForUserForm(forms.ModelForm):

    class Meta:
        model = topic
        fields = ['topic_name', 'research_direction', 'type', 'content']

    def save(self, commit=True):
        topic_post = self.instance
        topic_post.topic_name = self.cleaned_data['topic_name']
        topic_post.content = self.cleaned_data['content']
        topic_post.research_direction = self.cleaned_data['research_direction']
        topic_post.type = self.cleaned_data['type']

        if commit:
            topic_post.save()
        return topic_post


class EditTopicForSuperUserForm(forms.ModelForm):

    class Meta:
        model = topic
        fields = ['rate', 'review_date', 'process']

    def save(self, commit=True):
        topic_post = self.instance
        topic_post.rate = self.cleaned_data['rate']
        topic_post.review_date = self.cleaned_data['review_date']
        topic_post.process = self.cleaned_data['process']

        if commit:
            topic_post.save()
        return topic_post



TopicScientific/home/views.py
from django.shortcuts import render
from topics.views import get_topic_queryset
from topics.models import topic
# Create your views here.


def home(request):

    context = {}

    query = ""
    if request.GET:
        query = request.GET['q']
        context['query'] = str(query)

    topics = get_topic_queryset(query)
    context['topics'] = topics

    return render(request, 'topics/home.html', context)

TopicScientific/topics/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from topics.models import topic
from topics.forms import CreateTopicForm, EditTopicForUserForm, EditTopicForSuperUserForm
from accounts.models import Account
# Create your views here.


def create_topic_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = CreateTopicForm(request.POST)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=request.user.email).first()
        obj.author = author
        obj.save()
        form = CreateTopicForm()

    context['form'] = form

    return render(request, "topics/create_topic.html", context)


def detail_topic_view(request, slug):

    context = {}

    topics = get_object_or_404(topic, slug=slug)
    context['topic'] = topics

    return render(request, 'topics/detail_topic.html', context)


def edit_topic_view(request, slug):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    topic_post = get_object_or_404(topic, slug=slug)
    if request.POST:
        form = EditTopicForUserForm(request.POST or None, instance=topic_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Edited"
            topic_post = obj

    form = EditTopicForUserForm(
        initial={
            "topic_name": topic_post.topic_name,
            "content": topic_post.content,
            "research_direction": topic_post.research_direction,
            "type": topic_post.type,
        }
    )
    context['form'] = form

    return render(request, 'topics/edit_topic.html', context)


def edit_topic_super_user_view(request, slug):
    context = {}
    user = request.user
    if not user.is_superuser:
        return redirect('must_authenticate')

    topic_post = get_object_or_404(topic, slug=slug)
    if request.POST:
        form = EditTopicForSuperUserForm(request.POST or None, instance=topic_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Edited"
            topic_post = obj

    form = EditTopicForSuperUserForm(
        initial={
            "rate": topic_post.rate,
            "review_date": topic_post.review_date,
            "process": topic_post.process,
        }
    )
    context['form'] = form

    return render(request, 'topics/edit_topic_super_user.html', context)


def get_topic_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        topics = topic.objects.filter(
            Q(topic_name__contains=q)|
            Q(content__icontains=q)
            ).distinct()
        for topic in topics:
            queryset.append(topic)

    # create unique set and then convert to list
    return list(set(queryset))

TopicScientific/topics/templates/topics/create_topic.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" class="create-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Create</button>
    </form>
{% endblock %}

TopicScientific/topics/templates/topics/detail_topic.html
{% extends 'base.html' %}

{% block content %}
<h1>Title: {{ topic.topic_name }}</h1>
<h1>Author: {{ topic.author }}</h1>
<h1>Research {{ topic.research_direction }}</h1>
<h1>Type {{ topic.type }}</h1>
<h1>Process {{ topic.process }}</h1>
<h1>Rate {{ topic.rate }}</h1>
<h1>Review Date {{ topic.review_date }}</h1>
<h1>Content {{ topic.content |safe|linebreaks }}</h1>
{% if topic.author == request.user %}
<a href="{% url 'topic:edit' topic.slug %}">Edit</a>
{% endif %}
<h1> {{ topic.date_upload }} by {{ topic.author.username }}</h1>

{% endblock %}

TopicScientific/topics/templates/topics/edit_topic.html
{% extends 'base.html' %}

{% block content %}
            {% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}
        <form method="POST" class="create-form">{% csrf_token %}
        {{ form.as_p }}

                {% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

        <button type="submit" class="save btn btn-default">Edit</button>
        </form>

{% endblock content %}

TopicScientific/topics/templates/topics/edit_topic_super_user.html
{% extends 'base.html' %}

{% block content %}
            {% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}
        <form method="POST" class="create-form">{% csrf_token %}
        {{ form.as_p }}

                {% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

        <button type="submit" class="save btn btn-default">Edit</button>
        </form>

{% endblock content %}

TopicScientific/topics/templates/topics/home.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'topic:create' %}">Create topic</a>
<h1>List</h1>
{% for topic in topics %}
    <ul><a href="{% url 'topic:detail' topic.slug %}">Topic: {{topic.topic_name}}</a>
    <li class="list-group-item">Author: {{topic.author.username}}</li>
    <li class="list-group-item">Content: {{topic.content | safe |linebreaks}}</li>

    </ul>
{% if  request.user.is_superuser %}
<a href="{% url 'topic:edit_superuser' topic.slug %}">Edit</a>
{% endif %}
{% endfor %}


{% endblock %}